export default function ThemeIcon({ theme }) {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 20 20"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="theme-icon"
      style={{
        display: 'block',
        transition: 'transform 0.3s ease',
      }}
    >
      {theme === 'system' ? (
        <>
          <defs>
            <clipPath id="system-left-half">
              <rect x="0" y="0" width="10" height="20" />
            </clipPath>
            <clipPath id="system-right-half">
              <rect x="10" y="0" width="10" height="20" />
            </clipPath>
            <mask id="eclipse-mask">
              <rect width="20" height="20" fill="white" />
              <circle cx="12" cy="10" r="3.5" fill="black" />
            </mask>
          </defs>
          {/* Eclipsed sun - left half black, right half white */}
          {/* Left half - black */}
          <g clipPath="url(#system-left-half)">
            <circle
              cx="10"
              cy="10"
              r="4"
              fill="#000000"
              mask="url(#eclipse-mask)"
            />
            <g>
              <line
                x1="10"
                y1="2"
                x2="10"
                y2="1"
                stroke="#000000"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="10"
                y1="18"
                x2="10"
                y2="19"
                stroke="#000000"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="2"
                y1="10"
                x2="1"
                y2="10"
                stroke="#000000"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="18"
                y1="10"
                x2="19"
                y2="10"
                stroke="#000000"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="4.343"
                y1="4.343"
                x2="3.636"
                y2="3.636"
                stroke="#000000"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="15.657"
                y1="15.657"
                x2="16.364"
                y2="16.364"
                stroke="#000000"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="15.657"
                y1="4.343"
                x2="16.364"
                y2="3.636"
                stroke="#000000"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="4.343"
                y1="15.657"
                x2="3.636"
                y2="16.364"
                stroke="#000000"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
            </g>
          </g>
          {/* Right half - white */}
          <g clipPath="url(#system-right-half)">
            <circle
              cx="10"
              cy="10"
              r="4"
              fill="#ffffff"
              mask="url(#eclipse-mask)"
            />
            <g>
              <line
                x1="10"
                y1="2"
                x2="10"
                y2="1"
                stroke="#ffffff"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="10"
                y1="18"
                x2="10"
                y2="19"
                stroke="#ffffff"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="2"
                y1="10"
                x2="1"
                y2="10"
                stroke="#ffffff"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="18"
                y1="10"
                x2="19"
                y2="10"
                stroke="#ffffff"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="4.343"
                y1="4.343"
                x2="3.636"
                y2="3.636"
                stroke="#ffffff"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="15.657"
                y1="15.657"
                x2="16.364"
                y2="16.364"
                stroke="#ffffff"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="15.657"
                y1="4.343"
                x2="16.364"
                y2="3.636"
                stroke="#ffffff"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <line
                x1="4.343"
                y1="15.657"
                x2="3.636"
                y2="16.364"
                stroke="#ffffff"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
            </g>
          </g>
        </>
      ) : theme === 'light' ? (
        <>
          {/* Sun icon */}
          <circle
            cx="10"
            cy="10"
            r="4"
            fill="currentColor"
          />
          <g>
            <line
              x1="10"
              y1="2"
              x2="10"
              y2="1"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
            <line
              x1="10"
              y1="18"
              x2="10"
              y2="19"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
            <line
              x1="2"
              y1="10"
              x2="1"
              y2="10"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
            <line
              x1="18"
              y1="10"
              x2="19"
              y2="10"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
            <line
              x1="4.343"
              y1="4.343"
              x2="3.636"
              y2="3.636"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
            <line
              x1="15.657"
              y1="15.657"
              x2="16.364"
              y2="16.364"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
            <line
              x1="15.657"
              y1="4.343"
              x2="16.364"
              y2="3.636"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
            <line
              x1="4.343"
              y1="15.657"
              x2="3.636"
              y2="16.364"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
            />
          </g>
        </>
      ) : (
        <>
          <defs>
            <mask id="moon-mask">
              <rect width="20" height="20" fill="white" />
              <circle cx="12.5" cy="10" r="4" fill="black" />
            </mask>
          </defs>
          {/* Moon icon - crescent shape using mask */}
          <circle
            cx="10"
            cy="10"
            r="5"
            fill="currentColor"
            className="theme-icon-moon-dark"
            mask="url(#moon-mask)"
          />
          {/* Star */}
          <circle
            cx="11.5"
            cy="7.5"
            r="0.7"
            fill="currentColor"
            opacity="0.6"
            className="theme-icon-star-dark"
          />
        </>
      )}
    </svg>
  );
}

